# Generated by Django 5.2.8 on 2025-11-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPostVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=255)),
                ('direccion_vivienda', models.CharField(max_length=255)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_curso', 'En curso'), ('falta_material', 'Falta material'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_envio_correo', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_postventa', models.ManyToManyField(to='postventa.tipopostventa')),
            ],
        ),
    ]
