# Generated by Django 5.2.8 on 2025-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventa',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postventa',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
