# Generated by Django 5.2.8 on 2025-11-07 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0002_postventa_comentarios_postventa_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventa',
            name='numero_seguimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postventa',
            name='fecha_envio_correo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
