# Generated by AI Assistant on 2025-11-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0004_comite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nivel_acceso', models.CharField(choices=[('revisor', 'Revisor - Solo lectura'), ('usuario', 'Usuario - Gestiona sus propias post-ventas'), ('supervisor', 'Supervisor - Ve todas, edita las propias'), ('administrador', 'Administrador - Control total')], default='usuario', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puede_crear_postventa', models.BooleanField(default=True, help_text='Puede crear nuevas post-ventas')),
                ('puede_ver_todas_postventas', models.BooleanField(default=False, help_text='Puede ver todas las post-ventas')),
                ('puede_editar_todas_postventas', models.BooleanField(default=False, help_text='Puede editar todas las post-ventas')),
                ('puede_eliminar_todas_postventas', models.BooleanField(default=False, help_text='Puede eliminar todas las post-ventas')),
                ('puede_editar_propias_postventas', models.BooleanField(default=True, help_text='Puede editar sus propias post-ventas')),
                ('puede_eliminar_propias_postventas', models.BooleanField(default=True, help_text='Puede eliminar sus propias post-ventas')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, help_text='Puede gestionar usuarios')),
                ('puede_gestionar_comites', models.BooleanField(default=False, help_text='Puede gestionar comités')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'ordering': ['nombre'],
            },
        ),
    ]