# Generated by AI Assistant on 2025-11-12

from django.db import migrations


def create_default_tipos_usuario(apps, schema_editor):
    TipoUsuario = apps.get_model('postventa', 'TipoUsuario')
    
    # Crear tipos de usuario por defecto
    tipos_defaults = [
        {
            'nombre': 'Revisor',
            'nivel_acceso': 'revisor',
            'descripcion': 'Usuario que solo puede revisar las post-ventas sin realizar modificaciones. Ideal para auditores o supervisores que necesitan visualizar la información.',
            'puede_crear_postventa': False,
            'puede_ver_todas_postventas': True,
            'puede_editar_todas_postventas': False,
            'puede_eliminar_todas_postventas': False,
            'puede_editar_propias_postventas': False,
            'puede_eliminar_propias_postventas': False,
            'puede_gestionar_usuarios': False,
            'puede_gestionar_comites': False,
        },
        {
            'nombre': 'Usuario Básico',
            'nivel_acceso': 'usuario',
            'descripcion': 'Usuario estándar que puede gestionar únicamente sus propias post-ventas. Perfil ideal para usuarios finales.',
            'puede_crear_postventa': True,
            'puede_ver_todas_postventas': False,
            'puede_editar_todas_postventas': False,
            'puede_eliminar_todas_postventas': False,
            'puede_editar_propias_postventas': True,
            'puede_eliminar_propias_postventas': True,
            'puede_gestionar_usuarios': False,
            'puede_gestionar_comites': False,
        },
        {
            'nombre': 'Supervisor',
            'nivel_acceso': 'supervisor',
            'descripcion': 'Usuario con permisos extendidos que puede ver todas las post-ventas pero solo editar las propias. Ideal para coordinadores.',
            'puede_crear_postventa': True,
            'puede_ver_todas_postventas': True,
            'puede_editar_todas_postventas': False,
            'puede_eliminar_todas_postventas': False,
            'puede_editar_propias_postventas': True,
            'puede_eliminar_propias_postventas': True,
            'puede_gestionar_usuarios': False,
            'puede_gestionar_comites': False,
        },
        {
            'nombre': 'Administrador de Post-ventas',
            'nivel_acceso': 'administrador',
            'descripcion': 'Usuario con control total sobre las post-ventas pero sin permisos de gestión de usuarios.',
            'puede_crear_postventa': True,
            'puede_ver_todas_postventas': True,
            'puede_editar_todas_postventas': True,
            'puede_eliminar_todas_postventas': True,
            'puede_editar_propias_postventas': True,
            'puede_eliminar_propias_postventas': True,
            'puede_gestionar_usuarios': False,
            'puede_gestionar_comites': True,
        },
    ]
    
    for tipo_data in tipos_defaults:
        TipoUsuario.objects.get_or_create(nombre=tipo_data['nombre'], defaults=tipo_data)


def reverse_create_default_tipos_usuario(apps, schema_editor):
    TipoUsuario = apps.get_model('postventa', 'TipoUsuario')
    TipoUsuario.objects.filter(nombre__in=[
        'Revisor', 'Usuario Básico', 'Supervisor', 'Administrador de Post-ventas'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0005_tipousuario'),
    ]

    operations = [
        migrations.RunPython(create_default_tipos_usuario, reverse_create_default_tipos_usuario),
    ]