# Generated by Django 5.2.8 on 2025-11-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0006_create_default_tipos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventa',
            name='email_remitente',
            field=models.EmailField(blank=True, help_text='Email del remitente para contacto', max_length=254, null=True),
        ),
    ]
