# Generated by Django 5.2.8 on 2025-11-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0007_postventa_email_remitente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postventa',
            name='email_remitente',
        ),
    ]
